# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 17:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetapp', '0004_category_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybudgetgroup',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_budget_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_goals', to='budgetapp.Budget'),
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='long_term_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_goals', to='budgetapp.LongTermGoal'),
        ),
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='budgetapp.Category'),
        ),
        migrations.AlterField(
            model_name='categorybudget',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='budgetapp.CategoryBudgetGroup'),
        ),
        migrations.AlterField(
            model_name='categorybudgetgroup',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budget_groups', to='budgetapp.Budget'),
        ),
        migrations.AlterField(
            model_name='income',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='budgetapp.Budget'),
        ),
        migrations.AlterField(
            model_name='longtermgoal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgetapp.CategoryBudget'),
        ),
    ]
