# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetapp', '0010_auto_20170422_1105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('owner', 'name')]),
        ),
    ]
