# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetapp', '0012_auto_20170422_1946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together=set([('owner', 'category', 'group')]),
        ),
    ]
