# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-01 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetapp', '0014_auto_20170422_2039'),
    ]

    operations = [
        migrations.RenameModel('CategoryBudgetGroup', 'BudgetCategoryGroup'),
        migrations.RenameModel('CategoryBudget', 'BudgetCategory'),
        migrations.RenameField('Transaction', 'category_budget', 'budget_category')
    ]
