# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0016_auto_20180226_1944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together=set([('category', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategorygroup',
            unique_together=set([('name', 'budget')]),
        ),
        migrations.AlterUniqueTogether(
            name='budgetgoal',
            unique_together=set([('budget', 'long_term_goal')]),
        ),
        migrations.RemoveField(
            model_name='income',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='budgetcategorygroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='budgetgoal',
            name='owner',
        ),
    ]
