# Generated by Django 2.1.2 on 2018-10-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0019_auto_20181022_2226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together=set(),
        ),
    ]
