# Generated by Django 2.1.2 on 2018-11-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0020_auto_20181024_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
