# Generated by Django 2.1.2 on 2019-01-15 23:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetapp', '0023_payee_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payee',
            unique_together={('name', 'owner')},
        ),
    ]
