# Generated by Django 2.1.2 on 2019-01-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0024_payee_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='recipient',
            new_name='payee',
        ),
    ]
