# Generated by Django 2.1.2 on 2019-02-14 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0026_remove_budgetcategory_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='inflow',
        ),
    ]
